const esc = (s='') => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const source=(label,url)=>`<a class="text-link" href="${url}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`;
const repo='https://github.com/kaustubhkr/reinforcement-learning-toolkit';

// These diagrams explain source-backed interfaces, not measured execution traces.
const systems={
  race:{label:'Observation → policy → actuator',signature:'180 LiDAR bins → 25 coupled actions',steps:[['Observe','scan[180]','Sector minima retain nearby obstacles within the policy’s observation budget.'],['Decide','π(a | scan)','A discrete action binds steering and throttle into one control decision.'],['Execute','ROS 2 → AutoDRIVE','Publish the selected command; observe the next simulator state.'],['Evaluate','lap · collision · progress','Resets, checkpoints and evaluation make the same policy inspectable across runs.']],contracts:[['Observation','LiDAR geometry; no assumed direct speed measurement'],['Action','Coupled steering / throttle lookup'],['Continuation','ONNX, TensorRT and Triton tooling added in 2026']],feedback:'The action changes the next scan. Observation compression, action discretisation and reward shaping jointly define the racing controller.'},
  rl:{label:'RLx-Core / learning systems',signature:'Learn the update. Learn the dynamics.',steps:[['Optimise','H·Δθ = g','KL curvature, damped Hessian–vector products, conjugate gradients and a checked line search.'],['Estimate','10 critics · subset 2','Randomised value targets, UTD 20 and entropy-temperature learning.'],['Model','μϕ(s,a), log σ²ϕ(s,a)','JAX/Flax dynamics modules and Isaac Sim manipulation experiments.'],['Deploy','policy + runtime contract','An industrial deployment design for bounded inference and controller handover.']],contracts:[['Implemented','TRPO · PPO · TD3 · SAC · REDQ · DQN family'],['Experimental','MBPO modules · learned dynamics · Isaac Sim'],['Research','PETS · PlaNet · Dreamer · MuZero · SimPLe']],feedback:'Real experience → learned dynamics → imagined transitions → policy improvement. Model-based integration and latent world models extend the implemented model-free core.'},
  control:{label:'C++20 / fixed-period control',signature:'The actuator limit feeds back into state.',steps:[['Compute','u_raw = P + I + D + FF','Setpoint weighting, gain scheduling and Tustin-discretised derivative filtering.'],['Constrain','saturate → rate → jerk','Preserve each stage’s effect and the final applied command.'],['Reconcile','u_applied − u_raw','Feed constraint error into anti-windup; align internal state on transfer.'],['Supervise','health + watchdog','Track timing, limiting hits and fallback state with the output.']],contracts:[['Lifecycle','Initialise → start → update → stop / reset'],['Memory','Arena-allocated workspaces reused on the update path'],['Recording','JSONL · MCAP · FlatBuffers · integrity checks']],feedback:'Applied command → anti-windup correction → next integrator state. The controller’s memory follows what the actuator was allowed to do.'},
  runtime:{label:'ROS 2 Jazzy / command authority',signature:'One map. Three localisation owners.',steps:[['Localise','map → rᵢ/odom → rᵢ/base','Independent AMCL instances, initial-pose bootstrapping and world-to-map calibration.'],['Resolve','TF ownership + freshness','Detect competing transform publishers; expire stale sources after restart.'],['Arbitrate','raw intent → command gate','Combine mode, stop, interlock, warning and deliberate-restart state.'],['Record','final command + episode','A defined publisher owns motion output; rosbag2 captures the scenario and its inputs.']],contracts:[['Sensors','Front / rear LiDAR merging with explicit frame alignment'],['Stop path','A stale or blocking input prevents motion permission'],['Reproduction','Scenario, signal contracts, simulation clock and artifacts']],feedback:'A plausible transform is insufficient if its publisher has lost authority. Freshness and ownership are checked at both the frame and motion boundaries.'},
  evidence:{label:'Industrial recordings / compilation',signature:'Every value carries its origin.',steps:[['Preserve','raw bytes + source identity','Retain source recordings before protocol decoding or interpretation.'],['Decode','frames → canonical values','Map fields, track sequence gaps, duplicates, reordering, resets and incomplete fragments.'],['Align','time basis + source authority','Carry timestamp quality, source class, confidence and derivation into the timeline.'],['Compile','run bundle + replay','Package canonical records, quality summaries and provenance for repeatable analysis.']],contracts:[['Inputs','File logs · MCAP / rosbag2 · MQTT / OPC UA intake'],['Value contract','Observed value + timing + quality + provenance'],['Failure path','Integrity failures remain visible through quarantine and quality state']],feedback:'Preserved source → versioned interpretation → reproducible bundle. A new mapping can revisit the same recording without rewriting what was observed.'},
  verification:{label:'Temporal geometry / behavioural evidence',signature:'State × time × geometry → finding',steps:[['Align','bounded hold-last','Build analysis ticks while retaining gaps, event windows and freshness.'],['Ground','site model + robot footprint','Compute polygon membership, direction of travel and clearance to nearby structures.'],['Gate','required evidence → validator','Resolve dependencies before evaluating speed, warnings, restart or interlocks.'],['Explain','verdict + source window','Attach reason codes, severity and provenance to PASS, FAIL or NOT_VERIFIABLE.']],contracts:[['Geometry','Versioned site model and robot specification'],['Temporal rule','A stale sample cannot silently become fresh evidence'],['Output','Finding + evidence window + original source pointers']],feedback:'Missing, stale or insufficient observations propagate to NOT_VERIFIABLE. The finding preserves the exact physical context that made the rule applicable.'},
  vision:{label:'CARLA / representation transfer',signature:'Demonstrations become control features.',steps:[['Observe','RGB + additional channels','Five-channel input representation paired with expert controls.'],['Imitate','visual features → control heads','Transfer RGB features and train steering, throttle and brake predictions.'],['Reuse','checkpoint feature extractor','Carry the learned visual representation into an interaction-based agent.'],['Improve','visual features + vehicle state','Condition SAC on perception features and low-dimensional vehicle state.']],contracts:[['Learning stages','Supervised imitation → representation reuse → actor–critic'],['Control','Steering, throttle and brake predictions'],['Temporal scope','The current recurrent path receives a single timestep']],feedback:'A checkpoint is also a reusable representation. The next experiment asks what interaction can add to features first learned from expert driving.'},
  audio:{label:'Native macOS / local inference',signature:'Capture keeps running while models decode.',steps:[['Capture','AudioQueue · 20 ms PCM','A native 16 kHz audio path captures and buffers continuously.'],['Separate','screen audio ≠ microphone','ScreenCaptureKit and microphone capture retain independent stream paths.'],['Decode','bounded workers + GPU gate','Provisional transcription updates quickly; a separate final pass revisits the recording.'],['Remember','lossless chunks → SQLite','Persist recordings and local memory for later reconstruction.']],contracts:[['Concurrency','Audio callbacks are separate from inference work'],['Scheduling','Bounded local workers with serialised GPU work'],['Recovery','Retained audio supports independent final decoding']],feedback:'Capture → durable audio → provisional text → final decode. Transcript revision does not require losing or recapturing the original signal.'},
  compute:{label:'Private compute / session lifecycle',signature:'Host presence is not session authority.',steps:[['Register','host identity + heartbeat','Track whether a compute host is present and available.'],['Invite','expiring access','Bind a session invitation to a limited validity window.'],['Connect','authorised streaming session','Coordinate session access around an existing streaming layer.'],['Revoke','expiry + audit','End authority explicitly and retain session events.']],contracts:[['Control plane','Host registration, presence and invitation state'],['Lifecycle','Invite → connect → expire / revoke'],['Boundary','Session orchestration around an existing streaming protocol']],feedback:'A live heartbeat does not renew an expired invitation. Host availability and a user’s authority to connect remain separate state.'}
};
const systemFor=p=>systems[p.kind]||systems.compute;
const nodes=steps=>`<ol class="system-nodes">${steps.map(([title,code,description],i)=>`<li><span class="node-number mono">0${i+1}</span><h4>${esc(title)}</h4><code>${esc(code)}</code><p>${esc(description)}</p></li>`).join('')}</ol>`;
const contracts=rows=>`<dl class="system-contracts">${rows.map(([key,value])=>`<div><dt>${esc(key)}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl>`;
export function systemPreview(project){
  const s=systemFor(project);
  return `<div class="system-preview"><span class="mono preview-label">${esc(s.label)}</span><strong>${esc(s.signature)}</strong><div class="preview-nodes">${s.steps.map(([title,code],i)=>`<div><span class="mono">0${i+1} / ${esc(title)}</span><code>${esc(code)}</code></div>`).join('')}</div><span class="preview-feedback mono">↖ ${esc(s.contracts[0][1])}</span></div>`;
}
export function systemArchitecture(project){
  if(project.kind==='rl') return learningExplorer();
  const s=systemFor(project);
  return `<div class="system-board"><div class="board-title"><span class="mono">${esc(s.label)}</span><h3>${esc(s.signature)}</h3></div>${nodes(s.steps)}<p class="system-feedback"><span aria-hidden="true">↖</span>${esc(s.feedback)}</p>${contracts(s.contracts)}</div>`;
}

function tabs(id,label,items,defaultTab=items[0][0]){
  return `<div class="technical-explorer" data-tabs data-default="${defaultTab}"><div class="explorer-tabs" aria-label="${label}">${items.map(([key,title])=>`<button type="button" id="${id}-tab-${key}" data-tab="${key}" aria-controls="${id}-panel-${key}">${title}</button>`).join('')}</div>${items.map(([key,title,body])=>`<section class="explorer-panel" id="${id}-panel-${key}" data-panel="${key}" aria-labelledby="${id}-tab-${key}"><h3 class="no-js-tab-title">${title}</h3>${body}</section>`).join('')}</div>`;
}

function worldModels(){
  return `<div class="panel-heading"><span class="status-label">Experimental work · research direction</span><h3>Learn dynamics.<br>Reason over futures.</h3><p>RLx-Core extends from policies that map observations to actions into models that predict the consequences of those actions. My model-based branch starts with JAX/Flax components and a manipulation scene in Isaac Sim.</p></div>
  ${nodes([['Collect','(sₜ, aₜ, rₜ, sₜ₊₁)','Real transitions anchor the learning problem. The MBPO scaffold separates real and model replay.'],['Fit dynamics','μϕ(s,a), log σ²ϕ(s,a)','The implemented Flax module has independent mean and log-variance heads.'],['Branch rollouts','sₜ → ŝₜ₊₁ → … → ŝₜ₊ₖ','The MBPO design uses short model-generated trajectories; rollout-length ablations are configured.'],['Improve policy','real replay + model replay','The intended mixed-data update closes the loop. End-to-end integration remains in progress.']])}
  <div class="module-grid"><div><span class="mono">Modules I wrote</span><h4>Probabilistic dynamics + policy</h4><p>Dense JAX/Flax dynamics with separate mean and log-variance outputs. A tanh-squashed Gaussian policy, clipped log standard deviation and explicit PRNG splitting.</p></div><div><span class="mono">Simulation work</span><h4>Franka manipulation scene</h4><p>USD scene composition, articulated joints, rigid-body props, collision and friction configuration, surface-gripper control and joint-state input.</p></div></div>
  <div class="research-map"><div class="research-map-heading"><h4>World-model research track</h4><span class="mono">From the RLx / RLTK roadmap</span></div>${[
    ['MBPO','Short branched rollouts','Generate short synthetic trajectories from real replay states, then use them for policy improvement.','https://arxiv.org/abs/1906.08253'],
    ['PETS','Probabilistic dynamics for planning','Propagate model uncertainty through an ensemble and trajectory sampling when evaluating candidate actions.','https://arxiv.org/abs/1805.12114'],
    ['PlaNet','Latent-state planning','Encode observations into a recurrent latent state, then evaluate action sequences through learned dynamics.','https://arxiv.org/abs/1811.04551'],
    ['Dreamer V1 / V2 / V3','Learning in imagination','Use a learned world model to improve behaviour through imagined trajectories.','https://danijar.com/project/dreamerv3/'],
    ['MuZero','A learned model for search','Learn representations and dynamics that support reward, value and policy prediction during planning.','https://arxiv.org/abs/1911.08265'],
    ['SimPLe','Visual prediction for policy learning','Train a video-prediction model of the environment, then use the learned simulator to improve a policy.','https://arxiv.org/abs/1903.00374']
  ].map(([name,title,copy,url])=>`<div class="research-row"><div><strong>${name}</strong><span class="mono">Research track</span></div><div><h5>${title}</h5><p>${copy}</p></div>${source('Reference',url)}</div>`).join('')}</div>
  <p class="panel-context">The public branch contains the dynamics and policy modules, MBPO scaffolding and Isaac Sim scene work. Ensemble training, synthetic-rollout integration and full latent-agent training are further work in this track.</p><div class="source-links">${source('Model-based branch',repo+'/tree/main/phase_06_model_based/1_MBPO')}${source('Research roadmap',repo+'#algorithms--roadmap-phases')}</div>`;
}

function policyUpdates(){
  return `<div class="panel-heading"><span class="status-label">Implemented algorithm core</span><h3>The update is<br>part of the system.</h3><p>Curvature, target bias and data reuse are explicit in these implementations. The interesting part is what happens between collecting a transition and accepting a new policy.</p></div>
  <div class="algorithm-block"><div class="algorithm-heading"><span class="mono">01 / TRPO</span><h4>Curvature without a dense Hessian</h4></div><div class="equation"><span>(H<sub>KL</sub> + λI) Δθ = g</span><small>Hessian–vector products + conjugate gradients</small></div>${nodes([['Differentiate','g = ∇θ L(θ)','Flatten autograd derivatives of the policy-ratio surrogate.'],['Solve','v → Hₖₗv + λv','Differentiate the gradient–vector product; solve iteratively with residual-based termination.'],['Scale','½ ΔθᵀHΔθ ≤ δ','Scale the candidate step using the KL curvature estimate.'],['Accept / revert','KL budget ∧ improvement','Backtrack until the surrogate improves inside the trust region; restore the old parameters if no candidate passes.']])}</div>
  <div class="algorithm-block"><div class="algorithm-heading"><span class="mono">02 / REDQ</span><h4>Reuse experience without one critic owning the target</h4></div><div class="critic-bank" aria-label="Ensemble of 10 critics; illustration of a sampled subset of 2">${Array.from({length:10},(_,i)=>`<span${[2,7].includes(i)?' class="sampled"':''}>Q<sub>${i+1}</sub></span>`).join('')}</div><p class="diagram-caption">Illustrative subset selection: two critics contribute to the target minimum; the policy objective uses the ensemble mean.</p><div class="config-strip"><div><strong>10</strong><span>Critic networks</span></div><div><strong>2</strong><span>Target subset</span></div><div><strong>20</strong><span>Configured UTD</span></div></div><p class="algorithm-copy">Randomise the target subset, regress the critic ensemble, optimise the policy against the mean Q estimate, learn the entropy temperature, then softly update the target networks.</p></div>
  <div class="source-links">${source('TRPO update and line search',repo+'/tree/main/phase_04_pg/3_trpo/trpo')}${source('REDQ implementation',repo+'/tree/main/phase_05_actor_critic/3_redq/REDQ')}</div>`;
}

function operatingModes(){
  return `<div class="mode-inspector"><h4>How the learned policy gets control authority</h4>${tabs('mode','Policy operating mode',[
    ['shadow','Shadow','<span class="mode-formula">u = u<sub>classical</sub></span><p>The learned policy observes and logs counterfactual actions. The classical controller retains command authority.</p><span class="mode-rule">Compare proposed actions with the actual execution before handover.</span>'],
    ['residual','Residual','<span class="mode-formula">u = guard(u<sub>classical</sub> + Δu<sub>policy</sub>)</span><p>The learned policy contributes a bounded correction over the classical controller. The combined command passes through the actuator envelope.</p><span class="mode-rule">Bound the residual and define the trigger for returning to the classical controller.</span>'],
    ['primary','Primary','<span class="mode-formula">u = guard(u<sub>policy</sub>)</span><p>The learned policy supplies the main action within the declared execution envelope. Deadline, novelty and input monitors can request fallback.</p><span class="mode-rule">Control authority depends on runtime validity and a defined takeover path.</span>'],
    ['cooperative','Cooperative','<span class="mode-formula">u = guard(blend(u<sub>classical</sub>, u<sub>policy</sub>))</span><p>A scheduler coordinates the contribution of classical and learned policies. Blending and transitions become explicit parts of the controller design.</p><span class="mode-rule">The scheduler owns the handover; actuator constraints still apply to the result.</span>']
  ],'shadow')}</div>`;
}

function runtimeContract(){
  return `<div class="panel-heading"><span class="status-label">Deployment architecture · specified in README</span><h3>A policy export<br>is a control interface.</h3><p>The industrial design carries a trained policy into an inference-only runtime with declared shapes, normalisation, action bounds, timing and fallback responsibilities.</p></div>${nodes([['Train','Python / JAX → frozen parameters','Version the experiment, data assumptions and policy checkpoint.'],['Package','model.onnx + metadata.json','Bind the exported graph to the observation/action contract and model hash.'],['Execute','acquire → normalise → infer','A fixed-tick C++20 runtime with preallocated working buffers is the target execution design.'],['Constrain','clamp → rate / jerk → action','Monitor validity and timing; signal the classical-control path when takeover is required.']])}
  <h4 class="contract-heading">What travels with the model</h4>${contracts([['abi_version · dimensions','Interface version, obs_dim and act_dim define compatibility.'],['obs_norm · preprocess','The runtime receives the same normalisation and preprocessing used in training.'],['act_bounds · tick_hz','Action limits and the expected control period are explicit.'],['training_commit · onnx_sha256','The binary resolves to a particular training revision and content hash.'],['kpi_ref · license','Evaluation context and usage terms travel with the artifact.']])}
  ${operatingModes()}
  <div class="acceptance-targets"><span class="mono">README acceptance targets</span><p>Python/C++ parity ≤ 10⁻⁵ L∞; p95 inference ≤ 2 ms on reference hardware; zero post-init allocations; no missed ticks at the target rate; comparison against a classical baseline.</p><small>These are design gates for the deployment track, not reported benchmark results.</small></div><div class="source-links">${source('Deployment model contract',repo+'#deployment-model-contract')}${source('Related C++ control implementation','https://github.com/kaustubhkr/industrial-control-toolkit')}</div>`;
}

export function learningExplorer(){
  return `<div class="learning-system"><div class="board-title"><span class="mono">RLx-Core / Reinforcement Learning Toolkit</span><h2>From policy updates<br>to world models.</h2></div>${tabs('learning','Explore the learning architecture',[
    ['world-models','World models',worldModels()],
    ['policy','Policy optimisation',policyUpdates()],
    ['runtime','Runtime contract',runtimeContract()]
  ],'world-models')}</div>`;
}
