import { readFileSync } from 'node:fs';
const source='https://github.com/kaustubhkr/industrial-control-toolkit/blob/main/';
const figure=(file,alt,caption)=>`<figure class="measurement-figure"><img src="../assets/${file}" alt="${alt}" loading="lazy"><figcaption>${caption}</figcaption></figure>`;
export function projectEvidence(p){
  if(p.id==='autonomous-racing')return `<section id="evidence" class="evidence-section"><span class="eyebrow">Competition record</span><h2>Built and submitted independently.</h2><p>I designed, trained, integrated, evaluated and submitted the controller. The 2025 competition stack covered the ROS 2/Gymnasium bridge, observations, steering–throttle actions, rewards and checkpoints. ONNX, TensorRT and Triton inference tooling followed in 2026.</p><div class="round-results"><div><strong>Qualification · 3rd</strong><p>81.32 s total · 0 collisions · 8.03 s best lap.</p></div><div><strong>Final time attack · 14th</strong><p>A separate run on a different track.</p></div></div><p>Placed ahead of entries from Autonomous Racing at Penn and the Autoware Foundation in qualification, using the official collision-adjusted standings.</p><a class="button" href="https://autodrive-ecosystem.github.io/competitions/roboracer-sim-racing-icra-2025/#results" target="_blank" rel="noopener noreferrer">Official results & full standings ↗</a></section>`;
  if(p.id==='control-runtime'){
    const rows=readFileSync(new URL('../content/evidence/pid-benchmark.csv',import.meta.url),'utf8').split('\n').filter(x=>/^pid,/.test(x)).map(x=>x.split(',').map(y=>y.trim()));
    return `<section id="evidence" class="evidence-section"><span class="eyebrow">Recorded measurements</span><h2>Control response.<br>Execution cost.</h2><p>Position tracking, cascade response and controller-update timing from the toolkit’s recorded CSV artifacts.</p><div data-tabs data-default="response" class="measurement-tabs"><div class="explorer-tabs" aria-label="Control measurements"><button data-tab="response" id="tab-response" aria-controls="panel-response">Step response</button><button data-tab="latency" id="tab-latency" aria-controls="panel-latency">Latency</button></div><div class="explorer-panel" data-panel="response" id="panel-response" aria-labelledby="tab-response"><h3 class="no-js-tab-title">Step response</h3>${figure('control-response.svg','Position response and applied command across 1000 samples, including the setpoint and 2 percent settling band','Position-control example · 1 ms model step · 1,000 samples. Recorded response enters and stays in the ±2% band at 342 ms. This is a simulated integrator plant.')}${figure('control-cascade.svg','Cascade position and velocity response with the applied actuator command','Cascade example · 1 ms model step · 1,000 samples. Position overshoot 0.0904%; ±2% settling at 420 ms.')}<div class="source-links"><a href="../evidence/pid-position.csv" download>Position CSV ↓</a><a href="../evidence/pid-cascade.csv" download>Cascade CSV ↓</a><a href="${source}examples/pid/pid_position_control.cpp" target="_blank" rel="noopener noreferrer">Plant & controller configuration ↗</a></div></div><div class="explorer-panel" data-panel="latency" id="panel-latency" aria-labelledby="tab-latency"><h3 class="no-js-tab-title">Latency</h3>${figure('control-latency.svg','Recorded p50 p95 and p99 nanoseconds per update for 1 4 8 16 32 and 64 channels, showing both recorded sweeps','Raw PID + loop + timer measurements from both recorded sweeps. Each record summarises 200,000 timing batches, with 64 updates per batch after 10,000 warm-up updates.')}<p class="measurement-context">This is an amortised update microbenchmark, not scheduler jitter or end-to-end robot latency. Hardware identity and run flags are absent from the CSV. The two recorded sweeps are shown separately; neither is labelled as a safety-on/off comparison.</p><details class="measurement-table"><summary>Exact recorded percentiles</summary><div class="table-scroll"><table><thead><tr><th>Sweep</th><th>Channels</th><th>p50 ns</th><th>p95 ns</th><th>p99 ns</th><th>p99.9 ns</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i<6?'A':'B'}</td><td>${r[1]}</td><td>${r[4]}</td><td>${r[5]}</td><td>${r[6]}</td><td>${r[7]}</td></tr>`).join('')}</tbody></table></div></details><div class="source-links"><a href="../evidence/pid-benchmark.csv" download>Original benchmark CSV ↓</a><a href="${source}benchmarks/runners/bench_pid_vs_baseline.cc" target="_blank" rel="noopener noreferrer">Benchmark method ↗</a></div></div></div></section>`;
  }
  return '';
}
