import { readFileSync } from 'node:fs';
import { systemPreview, systemArchitecture } from './engineering.mjs';
import { projectEvidence } from './evidence.mjs';

const esc = (s='') => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const external = (label,url,cls='text-link') => `<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} <span aria-hidden="true">↗</span></a>`;
const email = 'kaustubhkr.work@gmail.com';
const canonical = 'https://kaustubhkr.github.io/';
const list = (items,cls='technical-list') => `<ul class="${cls}">${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
const link = (label,path,cls='text-link') => `<a class="${cls}" href="${path}">${label} <span aria-hidden="true">↗</span></a>`;

function header(p,active='') {
  return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><a class="identity" href="${p}index.html" aria-label="Kaustubh Krishna, home"><span class="monogram" aria-hidden="true">k<span>k</span></span><span>Kaustubh Krishna</span></a><nav aria-label="Main navigation">${[['Work','work.html'],['Direction','direction.html'],['About','about.html']].map(([name,path])=>`<a href="${p}${path}"${active===name?' aria-current="page"':''}>${name}</a>`).join('')}<a class="contact-nav" href="mailto:${email}">Get in touch <span aria-hidden="true">↗</span></a></nav></header>`;
}
function footer(p) {
  return `<footer class="wrap"><a href="${p}index.html">© 2026 Kaustubh Krishna</a><div class="footer-links">${external('GitHub','https://github.com/kaustubhkr')}${external('LinkedIn','https://linkedin.com/in/kaustubhkrishna')}<a href="mailto:${email}">Email ↗</a><a href="#main" class="back-top" aria-label="Back to top">↑</a></div></footer>`;
}
function layout({path,title,description,body,active=''}) {
  const p=path==='404.html'?canonical:(path.includes('/')?'../':'./');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#10120f"><title>${esc(title)} · Kaustubh Krishna</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}${path==='index.html'?'':path}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)} · Kaustubh Krishna"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}${path==='index.html'?'':path}"><meta property="og:image" content="${canonical}assets/racing-poster.jpg"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="${p}favicon.svg"><link rel="stylesheet" href="${p}styles.css"><script src="${p}app.js" defer></script></head><body>${header(p,active)}<main id="main">${body}</main>${footer(p)}</body></html>`;
}

function projectCard(p,base='./',compact=false) {
  return `<article class="project-card${compact?' compact-card':''}"><a class="project-visual${p.kind==='race'?' racing-visual':''}" href="${base}projects/${p.id}.html" aria-label="Read ${esc(p.name)}">${p.kind==='race'?`<img src="${base}assets/racing-poster.jpg" alt="" width="1120" height="630" loading="lazy"><span class="visual-caption mono">ICRA 2025 / Qualification footage</span>`:systemPreview(p)}</a><div class="card-meta mono"><span>${p.number} / ${esc(p.category)}</span><span>${p.repo?'Public repository':'Private work'}</span></div><h3><a href="${base}projects/${p.id}.html">${esc(p.title)} <span aria-hidden="true">↗</span></a></h3><p class="project-name">${esc(p.name)}</p>${list(compact?p.bullets.slice(0,p.id==='autonomous-racing'?3:2):p.bullets,'card-bullets')}${p.relatedId?`<p class="related-project">${link(esc(p.relatedLabel),base+'projects/'+p.relatedId+'.html')}</p>`:''}<div class="card-bottom"><span class="mono">${esc(p.tags.slice(0,2).join(' / '))}</span>${link('Inside the system',base+'projects/'+p.id+'.html')}</div></article>`;
}
const timeline=[
  ['~2016','Age 10','Started writing code.','Curiosity turned into electronics, robot mechanisms, sensors and closed-loop control.'],
  ['2018–2022','Ages 12–16','Built robots. Put them to the test.','WRO India: regional participation in 2018, regional Junior second place in 2019, and a RoboMission Senior Silver Badge at the 2022 National Championship.'],
  ['2023–2024','Ages 17–18','Moved into autonomous vehicles.','Deployed autonomous-driving work on a physical golf cart with an RL adapter and industrial controls, alongside CARLA experiments and MPCC / modified PPO / SAC comparison.'],
  ['2025','Age 19','Built the ICRA racing controller independently.','Third in qualification in the ICRA RoboRacer Sim Racing League. An 81.32-second run, zero collisions and an 8.03-second best lap.'],
  ['2025–2026','Ages 19–20','Founded AviRob. Went into industrial systems.','Built robot runtimes, machine-evidence compilation and geometric verification. Spoke at ROSCon India 2025 about the AMR/AGV log and safety-evidence problem.'],
  ['2026','Turns 20','Building a second company in stealth.','Working on Physical AI for industry, toward machines and factories that can adapt, coordinate, recover and verify their work.']
];
const timelineHTML=(all=true)=>`<div class="timeline">${timeline.filter((_,i)=>all||i>0).map(([year,age,title,copy])=>`<div class="timeline-row"><div class="timeline-date"><span>${year}</span>${all?`<span class="mono">${age}</span>`:''}</div><div><h3>${title}</h3><p>${copy}</p></div></div>`).join('')}</div>`;

function contact(base='./') {
  return `<section class="wrap section contact-section" id="contact"><span class="eyebrow">Let’s build</span><div><h2>Hard problems.<br>Physical consequences.</h2><div><p>For robotics research, industrial autonomy and founder conversations.</p><a class="email-link" href="mailto:${email}">${email} ↗</a><div class="contact-links">${external('GitHub','https://github.com/kaustubhkr')}${external('LinkedIn','https://linkedin.com/in/kaustubhkrishna')}</div></div></div></section>`;
}

function home(projects) {
  return `<section class="hero wrap"><div class="hero-topline mono"><span>Physical AI · General industrial intelligence</span><span>Founder & builder / India</span></div><div class="hero-grid"><div class="hero-copy"><span class="founder-line mono">Second company / Building in stealth</span><h1>Building<br>toward<br><span>Industry 6.0.</span></h1><p class="hero-intro">I’m building my second company in Physical AI: factories that understand a production goal, coordinate machines and verify the result.</p><p class="hero-description">Previously founded AviRob. My work spans learned dynamics, policy optimisation, MPCC, control runtimes and industrial verification.</p><a class="button primary" href="#work">Explore my work <span aria-hidden="true">↘</span></a></div><div class="hero-media"><div class="media-top mono"><span>01 / Autonomous racing</span><span>ICRA 2025</span></div><div class="video-shell"><video id="hero-video" muted controls loop playsinline preload="metadata" poster="./assets/racing-poster.jpg" aria-label="AutoDRIVE autonomous racing, ICRA 2025 qualification footage"><source src="./assets/racing-loop.mp4" type="video/mp4"></video><button class="play-toggle" data-video="hero-video" hidden aria-label="Pause racing footage">Ⅱ</button></div><div class="race-caption"><div><span class="caption-title">Sole builder · ICRA qualification</span><span class="mono">ICRA 2025 · Simulation qualification</span><span class="conference-badge">IEEE RAS flagship conference</span><span class="conference-name">IEEE International Conference on Robotics and Automation</span></div><a class="round-link" href="./projects/autonomous-racing.html" aria-label="Read autonomous racing project">↗</a></div><div class="race-stats"><div><strong>03<span>rd</span></strong><span>In qualification</span></div><div><strong>0</strong><span>Collisions</span></div><div><strong>8.03<span>s</span></strong><span>Best lap</span></div></div></div></div><div class="hero-bottom mono"><span>Robotics · Learning · Industrial autonomy</span><a href="#work">Selected systems below ↓</a></div></section>
  <section class="wrap validation-strip" aria-label="External evidence"><a href="./projects/autonomous-racing.html"><span class="mono">ICRA 2025</span><strong>3rd in qualification</strong><span>81.32 s · zero collisions · sole builder</span></a><a href="https://www.youtube.com/watch?v=8RZy6ztm5Wg" target="_blank" rel="noopener noreferrer"><span class="mono">ROSCon India 2025</span><strong>Technical speaker</strong><span>AMR/AGV machine evidence architecture</span></a><a href="./about.html#timeline"><span class="mono">Robotics since childhood</span><strong>WRO → ICRA → founder</strong><span>Original footage and a dated timeline</span></a></section>
  <section class="wrap section" id="work"><div class="section-heading"><span class="eyebrow">01 / Selected work</span><h2>Built across<br>the entire loop.</h2><p>Systems across robot learning, control, coordination and verification. Original footage, recorded measurements and the engineering decisions behind them.</p></div><div class="project-grid">${projects.filter(p=>p.featured).map(p=>projectCard(p,'./',true)).join('')}</div><div class="archive-entry"><span class="mono">Beyond the flagship work</span><a href="./archive.html">Experiments & archive <span aria-hidden="true">↗</span></a><p>Visual driving, native inference and private compute.</p></div></section>
  <section class="wrap thesis-link"><span class="eyebrow">Technical thesis</span><h2>How does a production goal<br>become verified machine work?</h2><p>Task contracts, machine state, control authority and evidence. The architecture questions behind my current company.</p><a class="button" href="./direction.html">Read the technical thesis ↗</a></section>
  <section class="wrap section talk-section"><a class="talk-image" href="https://www.youtube.com/watch?v=8RZy6ztm5Wg" target="_blank" rel="noopener noreferrer" aria-label="Watch my ROSCon India 2025 talk"><img src="./assets/roscon-stage.jpg" alt="Kaustubh explaining the AMR and AGV monitoring architecture on stage at ROSCon India 2025" width="1200" height="674" loading="lazy"><span class="watch-pill">▶ Watch the talk</span></a><div><span class="eyebrow">On stage</span><h2>Inside AviRob’s<br>robot evidence stack.</h2><p>At ROSCon India 2025, I presented the architecture behind our AMR/AGV monitoring work: collecting fragmented logs, reconstructing machine behaviour and turning it into inspectable engineering evidence.</p>${external('ROSCon India 2025','https://www.youtube.com/watch?v=8RZy6ztm5Wg')}</div></section>${contact()}`;
}

function projectPage(project,projects) {
  const p=project;const group=projects.filter(x=>x.featured===p.featured&&!x.relatedTo);const next=p.relatedTo?projects.find(x=>x.id===p.relatedTo):group[(group.findIndex(x=>x.id===p.id)+1)%group.length];
  return `<section class="wrap page-intro project-intro"><a class="back-link mono" href="../${p.featured||p.relatedTo?'work':'archive'}.html">← ${p.featured||p.relatedTo?'Flagship work':'Experiments & archive'}</a><div class="detail-topline mono"><span>${p.number} / ${esc(p.category)}</span><span>${esc(p.year)}</span></div><h1>${esc(p.title)}</h1><p class="page-deck">${esc(p.subtitle)}</p><div class="project-facts"><div><span class="mono">System</span><strong>${esc(p.name)}</strong></div><div><span class="mono">My contribution</span><strong>${esc(p.role)}</strong></div><div><span class="mono">Access</span><strong>${esc(p.access)}</strong></div></div></section>
  <div class="wrap detail-layout"><aside class="detail-nav"><span class="eyebrow">Inside the system</span><nav aria-label="Project sections"><a href="#overview">Overview</a>${['race','control'].includes(p.kind)?'<a href="#evidence">Evidence</a>':''}<a href="#architecture">Architecture</a>${p.sections.map(([h],i)=>`<a href="#section-${i}">${esc(h)}</a>`).join('')}<a href="#engineering-note">Engineering note</a></nav>${p.repo?external('View implementation',p.repo,'button'):''}</aside><article class="project-body"><section id="overview"><span class="eyebrow">Overview</span><p class="lead-copy">${esc(p.lead)}</p>${list(p.bullets,'summary-bullets')}${p.relatedId?`<p class="related-project">${link(esc(p.relatedLabel),'./'+p.relatedId+'.html')}</p>`:''}${p.kind==='race'?`<figure class="project-media"><video controls playsinline preload="none" poster="../assets/racing-poster.jpg" aria-label="ICRA 2025 qualification footage excerpt"><source src="../assets/icra-qualification.mp4" type="video/mp4"></video><figcaption>ICRA 2025 RoboRacer Sim Racing League · qualification footage excerpt</figcaption></figure><div class="result-strip"><div><strong>81.32 s</strong><span>Qualification run</span></div><div><strong>0</strong><span>Collisions</span></div><div><strong>8.03 s</strong><span>Best lap</span></div></div>`:''}</section>${projectEvidence(p)}<section id="architecture"><span class="eyebrow">System architecture</span>${systemArchitecture(p)}</section>${p.sections.map(([h,items],i)=>`<section id="section-${i}"><span class="eyebrow">0${i+1} / ${esc(p.sectionLabels?.[i]||'Implementation')}</span><h2>${esc(h)}</h2>${list(items)}</section>`).join('')}<section class="engineering-note" id="engineering-note"><span class="eyebrow">Engineering note</span><h2>${esc(p.noteTitle)}</h2><p>${esc(p.note)}</p></section><section class="scope-note"><span class="mono">Project context</span><p>${esc(p.boundary)}</p><div class="source-links">${p.repo?external('Source on GitHub',p.repo):''}${p.links.map(([label,url])=>external(label,url)).join('')}</div></section></article></div><section class="wrap next-project"><span class="eyebrow">Keep exploring</span><a href="./${next.id}.html"><h2>${esc(next.title)}</h2><span aria-hidden="true">↗</span></a><p>${esc(next.name)}</p></section>`;
}

function about() {
  return `<section class="wrap page-intro"><span class="eyebrow">About / Kaustubh Krishna</span><h1>It started with<br>a robot on the floor.</h1><p class="page-deck">Born in 2006. Turning 20 in 2026. Building my second company in Physical AI.</p></section><section class="wrap about-opening"><figure><img src="./assets/early-robot.jpeg" alt="An early line-following robot with a front-mounted infrared sensor array" width="1280" height="960"><figcaption>Early hardware · a line follower and its infrared sensor array</figcaption></figure><div><p class="lead-copy">I started coding around ten, then built line followers and competition robots. In 2019, I placed second in the WRO India regional Junior category.</p><p>I moved into autonomous vehicles, visual learning and control. In 2025, I independently built the ICRA simulation-racing entry and presented my industrial robotics work at ROSCon India.</p><p>I founded AviRob, where I built robot runtimes and machine-evidence systems. I’m now building a second Physical AI company in stealth.</p></div></section>
  <section class="wrap section" id="timeline"><div class="section-heading"><span class="eyebrow">The timeline / age in each year</span><h2>A decade of<br>building through it.</h2><p>From the first robot to my second company, with original competition footage below.</p></div>${timelineHTML()}</section>
  <section class="wrap section"><div class="section-heading"><span class="eyebrow">Technical ground</span><h2>From optimisation<br>to the physical loop.</h2><p></p></div><div class="expertise-grid">${[['Learning & optimisation','Trust-region solvers, critic ensembles, learned dynamics, world-model research and representation transfer.'],['Motion & control','Model Predictive Contouring Control (MPCC), local planning, actuator constraints, anti-windup and bumpless controller transfer.'],['Robotics & runtime','ROS 2, Nav2, AMCL, multi-robot frames, LiDAR integration, command arbitration and deterministic recording.'],['Industrial & native systems','Machine evidence, temporal alignment, computational geometry, provenance and native C++20/Swift runtimes.']].map(([h,p])=>`<div><h3>${h}</h3><p>${p}</p></div>`).join('')}</div></section>
  <section class="wrap section"><div class="section-heading"><span class="eyebrow">From the archive</span><h2>The early loops.</h2><p>Original test footage from the years before autonomous racing and industrial systems.</p></div><div class="archive-grid"><figure><video controls playsinline preload="none" poster="./assets/early-robot.jpeg" aria-label="Early PID line-following robot test"><source src="./assets/early-pid.mp4" type="video/mp4"></video><figcaption>PID line-following test · personal project archive</figcaption></figure><figure><video controls playsinline preload="none" poster="./assets/wro-test-poster.jpg" aria-label="World Robot Olympiad robot test"><source src="./assets/wro-test.mp4" type="video/mp4"></video><figcaption>World Robot Olympiad robot test · personal project archive</figcaption></figure></div><details class="archive-detail"><summary>WRO India 2019 · regional Junior second place <span aria-hidden="true">+</span></summary><img src="./assets/wro-robot.jpeg" alt="WRO India 2019 plaque: second position, Junior Regional Championship" width="814" height="1280" loading="lazy"></details></section>
  ${contact()}`;
}
function direction() {
  return `<section class="wrap page-intro"><span class="eyebrow">Direction / Technical thesis</span><h1>Production intent.<br>Executable contracts.</h1><p class="page-deck">My thesis: industrial intelligence needs a representation that connects an intended physical outcome to machine actions and independently observed evidence.</p></section><section class="wrap thesis-contract"><span class="mono">The unit of execution</span><code>task = outcome + constraints + preconditions + actions + acceptance</code><p>A task is complete when its acceptance conditions are observed. A command acknowledgement is only one event in that process.</p></section><section class="wrap section"><div class="direction-questions">${[
['01','Represent the physical outcome.','Define target state, frame, tolerances and observations. Compile a process graph with preconditions and effects. Unknown units, geometry or capabilities block execution.'],
['02','Resolve action against machine state.','Bind each step to an available resource and valid mode. Separate planning, supervision and servo timescales. Make final motion authority explicit across learned and classical controllers.'],
['03','Use prediction where it changes action.','Use learned dynamics to choose actions, estimate contact or evaluate recovery. Measure rollout error and decision quality under hidden state and distribution shift.'],
['04','Recover without losing the contract.','Preserve completed effects and remaining capabilities after divergence. Resume from verified preconditions; invalidate dependent steps when physical state changes.'],
['05','Carry evidence into the next deployment.','Bind results to observations, timing, model identity and machine configuration. Measure adaptation effort and task success on a changed cell to establish transfer.']
].map(([n,h,p])=>`<div class="direction-question"><span class="mono">${n}</span><div><h3>${h}</h3><p>${p}</p></div></div>`).join('')}</div></section><section class="wrap section"><span class="eyebrow">Evaluation questions</span><div class="thesis-tests"><div><h3>Can the task transfer?</h3><p>Hold the outcome fixed, change a machine or fixture, then measure mapping effort, recovery and acceptance.</p></div><div><h3>Can failure be detected?</h3><p>Introduce stale state, interrupted motion or a missing observation. Check whether execution stops, recovers or withholds a verdict.</p></div><div><h3>Does learning improve decisions?</h3><p>Compare learned and classical choices under the same task constraints, including tail latency and failure cases.</p></div></div><p class="direction-closing">This is the technical direction of my second company. The <a href="./work.html" class="text-link">flagship case studies ↗</a> show the systems I have built so far.</p></section>${contact()}`;
}

export function renderSite(root) {
  const projects=JSON.parse(readFileSync(root+'/content/projects.json','utf8'));
  const pages=new Map();
  const add=(path,title,description,body,active='')=>pages.set(path,layout({path,title,description,body,active}));
  add('index.html','Founder · Physical AI · Industry 6.0','Kaustubh Krishna is building his second company in Physical AI, toward Industry 6.0 and autonomous factories. Founder of AviRob; learning, control and industrial systems.',home(projects));
  add('work.html','Selected work','Flagship systems across robot learning, constrained control, multi-robot autonomy and industrial evidence.',`<section class="wrap page-intro"><span class="eyebrow">Work / 2024–2026</span><h1>From the update rule<br>to the machine.</h1><p class="page-deck">Independent systems. Measured control behaviour, original racing footage, learning experiments and selected private robotics work. <a class="text-link" href="./archive.html">Experiments & archive ↗</a></p><div class="work-index-links">${projects.filter(p=>p.featured).map(p=>`<a href="#${p.id}" class="mono">${p.number} / ${esc(p.name)} ↓</a>`).join('')}</div></section><section class="wrap section work-list"><div class="project-grid">${projects.filter(p=>p.featured).map(p=>`<div id="${p.id}">${projectCard(p)}</div>`).join('')}</div></section>`, 'Work');
  add('archive.html','Experiments & archive','Visual driving, native speech inference and private compute experiments.',`<section class="wrap page-intro"><span class="eyebrow">Experiments & archive</span><h1>Other systems.<br>Same curiosity.</h1><p class="page-deck">Work in visual driving, native inference and access infrastructure, alongside the main robotics programme.</p><a class="text-link" href="./work.html">Back to flagship work ↗</a></section><section class="wrap section"><div class="project-grid">${projects.filter(p=>!p.featured&&!p.relatedTo).map(p=>projectCard(p)).join('')}</div></section>`,'Work');
  add('about.html','About','From early robotics and World Robot Olympiad to ICRA autonomous racing, AviRob and a second Physical AI company in stealth.',about(),'About');
  add('direction.html','Industry 6.0 & autonomous factories','Building toward general industrial intelligence: systems that interpret production goals, coordinate machines, recover and verify physical outcomes.',direction(),'Direction');
  for(const p of projects) add('projects/'+p.id+'.html',p.name,p.subtitle,projectPage(p,projects),'Work');
  pages.set('rlx-core.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0;url=./projects/reinforcement-learning.html"><link rel="canonical" href="${canonical}projects/reinforcement-learning.html"><title>Reinforcement Learning Toolkit · Kaustubh Krishna</title></head><body><p>This project is now the <a href="./projects/reinforcement-learning.html">Reinforcement Learning Toolkit</a>.</p></body></html>`);
  add('404.html','Page not found','Find Kaustubh Krishna’s projects in robotics and Physical AI.',`<section class="wrap page-intro"><span class="eyebrow">404 / Unmapped territory</span><h1>Let’s get you<br>back on track.</h1><p class="page-deck">That page has moved or doesn’t exist.</p>${link('Explore the work',canonical+'work.html','button primary')}</section>`);
  return pages;
}
