import { readFileSync } from 'node:fs';
import { systemPreview, systemArchitecture } from './engineering.mjs';
import { projectEvidence } from './evidence.mjs';
import { contextDocuments } from './context.mjs';

const esc = (s='') => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const external = (label,url,cls='text-link') => `<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} <span aria-hidden="true">↗</span></a>`;
const email = 'kaustubhkr.work@gmail.com';
const canonical = 'https://kaustubhkr.github.io/';
const list = (items,cls='technical-list') => `<ul class="${cls}">${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
const link = (label,path,cls='text-link') => `<a class="${cls}" href="${path}">${label} <span aria-hidden="true">↗</span></a>`;

function header(p,active='') {
  return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><a class="identity" href="${p}index.html" aria-label="Kaustubh Krishna, home"><span class="monogram" aria-hidden="true">k<span>k</span></span><span>Kaustubh Krishna</span></a><nav aria-label="Main navigation">${[['Work','work.html'],['Life so far','about.html']].map(([name,path])=>`<a href="${p}${path}"${active===name?' aria-current="page"':''}>${name}</a>`).join('')}<a class="contact-nav" href="mailto:${email}">Get in touch <span aria-hidden="true">↗</span></a></nav></header>`;
}
function footer(p) {
  return `<footer class="wrap"><a href="${p}index.html">© 2026 Kaustubh Krishna</a><div class="footer-links">${external('GitHub','https://github.com/kaustubhkr')}${external('LinkedIn','https://linkedin.com/in/kaustubhkrishna')}<a href="mailto:${email}">Email ↗</a><a href="${p}full-context.html">Full context / for agents ↗</a><a href="#main" class="back-top" aria-label="Back to top">↑</a></div></footer>`;
}
function layout({path,title,description,body,active=''}) {
  const p=path==='404.html'?canonical:(path.includes('/')?'../':'./');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#10120f"><title>${esc(title)} · Kaustubh Krishna</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}${path==='index.html'?'':path}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)} · Kaustubh Krishna"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}${path==='index.html'?'':path}"><meta property="og:image" content="${canonical}assets/racing-poster.jpg"><meta name="twitter:card" content="summary_large_image"><link rel="alternate" type="text/plain" title="Complete portfolio context" href="${p}llms-full.txt"><link rel="describedby" type="text/plain" title="Agent reading index" href="${p}llms.txt"><link rel="icon" href="${p}favicon.svg"><link rel="stylesheet" href="${p}styles.css"><script src="${p}app.js" defer></script></head><body>${header(p,active)}<main id="main">${body}</main>${footer(p)}</body></html>`;
}

function projectCard(p,base='./',compact=false) {
  return `<article class="project-card${compact?' compact-card':''}"><a class="project-visual${p.kind==='race'?' racing-visual':''}" href="${base}projects/${p.id}.html" aria-label="Read ${esc(p.name)}">${p.kind==='race'?`<img src="${base}assets/racing-poster.jpg" alt="" width="1120" height="630" loading="lazy"><span class="visual-caption mono">ICRA 2025 / Qualification footage</span>`:systemPreview(p)}</a><div class="card-meta mono"><span>${p.number} / ${esc(p.category)}</span><span>${p.repo?'Public repository':'Private work'}</span></div><h3><a href="${base}projects/${p.id}.html">${esc(p.title)} <span aria-hidden="true">↗</span></a></h3><p class="project-name">${esc(p.name)}</p>${list(compact?p.bullets.slice(0,p.id==='autonomous-racing'?3:2):p.bullets,'card-bullets')}${p.relatedId?`<p class="related-project">${link(esc(p.relatedLabel),base+'projects/'+p.relatedId+'.html')}</p>`:''}<div class="card-bottom"><span class="mono">${esc(p.tags.slice(0,2).join(' / '))}</span>${link('Inside the system',base+'projects/'+p.id+'.html')}</div></article>`;
}
const timeline=[
  ['2006','Born','Hello World!','Arrived without a manual. Made myself heard.'],
  ['Early years','','Learned to walk. Learned to talk.','Balance took a few iterations. Talking was harder to switch off.'],
  ['2014','Age 8','Two computers. Unlimited plans.','Intel Pentium dual-core. 2 GB RAM each. 28–100 GB HDDs. My first compute cluster, if you’re generous.'],
  ['2015','Age 9','First programs.','Scratch, QBasic and web development. Things moved on screen because I told them to. This seemed like a loophole.'],
  ['2016','Age 10','Java. My first proper language.','Hello World now required a class.'],
  ['2018–2022','Ages 12–16','The code grew wheels.','WRO India: regional Junior second place in 2019; RoboMission Senior Silver Badge at nationals in 2022. Bugs could now leave the desk.'],
  ['2022','Age 16','First heartbreak.','No stack trace. Terrible documentation.'],
  ['2023–2024','Ages 17–18','The wheels got bigger.','Deployed autonomy on a real golf cart: Model Predictive Contouring Control (MPCC), learned policies and industrial controls. No simulator reset button.'],
  ['2025','Age 19','Raced robots. Spoke to humans.','Built my ICRA racing entry solo: third in simulation qualification, zero collisions. Presented industrial robotics work at ROSCon India.'],
  ['2025–2026','Ages 19–20','First startup: AviRob.','Built robot runtimes and machine-evidence systems. Discovered that companies have rather a lot of non-code problems.'],
  ['2026','Age 20','Second company. Still building.','Physical AI for industry, in stealth. Apparently one startup was not enough character development.']
];
const golfCartMedia=(base,compact=false)=>`<figure class="project-media${compact?' timeline-media':''}"${compact?' id="golf-cart-photo"':''}><img src="${base}assets/golf-cart.jpg" alt="Kaustubh and the project team with the physical autonomous golf cart" width="863" height="648" loading="lazy"><figcaption>The real golf cart, with the team. ${compact?link('Inside the build','./projects/golf-cart.html'): 'Physical vehicle project · separate from ICRA racing.'}</figcaption></figure>`;
const amrMedia=(base,compact=false)=>`<figure class="project-media${compact?' timeline-media':''}"${compact?' id="avirob-demo"':''}><video controls muted playsinline preload="none" poster="${base}assets/avirob-isaac-sim-poster.jpg" aria-label="AviRob Isaac Sim warehouse demo with three mobile robots"><source src="${base}assets/avirob-isaac-sim.mp4" type="video/mp4"></video><figcaption>AviRob · three-robot warehouse demo in Isaac Sim · silent. ${compact?link('Inside the runtime','./projects/multi-robot-runtime.html'): 'Simulation footage from the original AviRob deck.'}</figcaption></figure>`;
const timelineHTML=(all=true)=>`<div class="timeline">${timeline.filter((_,i)=>all||i>0).map(([year,age,title,copy])=>`<div class="timeline-row"><div class="timeline-date"><span>${year}</span>${all&&age?`<span class="mono">${age}</span>`:''}</div><div><h3>${title}</h3><p>${copy}</p>${year==='2023–2024'?golfCartMedia('./',true):year==='2025–2026'?amrMedia('./',true):''}</div></div>`).join('')}</div>`;

function contact() {
  return `<section class="wrap compact-contact" id="contact"><div><span class="eyebrow">Contact</span><h2>Kaustubh Krishna</h2><p>Founder · robotics & industrial autonomy · India</p></div><a class="email-link" href="mailto:${email}">${email} ↗</a></section>`;
}

function reviewCard(p,base='./') {
  const r=p.review;
  return `<article class="review-card" id="${p.id}"><div><span class="eyebrow">${esc(p.category)}</span><h3>${link(esc(r.title),base+'projects/'+p.id+'.html')}</h3></div><div><p class="review-outcome">${esc(r.outcome)}</p><p class="review-mechanism">${esc(r.mechanism)}</p><p class="review-proof">${esc(r.evidence)}</p><div class="source-links">${link('Technical case study',base+'projects/'+p.id+'.html')}${p.repo?external('Code',p.repo):''}${p.id==='machine-evidence'?external('ROSCon talk','https://www.youtube.com/watch?v=8RZy6ztm5Wg'):''}${p.id==='control-runtime'?link('Measurements',base+'projects/'+p.id+'.html#evidence'):''}</div></div></article>`;
}

function home(projects) {
  return `<div class="review-home"><section class="hero wrap"><div class="hero-topline mono"><span>Kaustubh Krishna / Founder & engineer</span><span>Physical AI / India</span></div><div class="hero-grid"><div class="hero-copy"><h1>I build systems<br>that <span>control<br>physical machines.</span></h1><p class="hero-intro">Autonomous vehicles, robot learning and industrial verification. Now building a Physical AI company around production goals, machine execution and verified outcomes.</p><p class="hero-description">Previously founded AviRob. I work across learning algorithms, control runtimes and the evidence needed to understand what a machine actually did.</p><div class="hero-actions"><a class="button primary" href="#work">Selected work ↓</a>${link('View life story','./about.html')}</div><p class="agent-reading-note">For AI readers: ${link('read the full portfolio','./full-context.html')} or ${link('fetch all text','./llms-full.txt')} for every project, result and technical detail.</p></div><div class="hero-media"><div class="media-top mono"><span>ICRA 2025 / Autonomous racing</span></div><div class="video-shell"><video id="hero-video" muted controls loop playsinline preload="metadata" poster="./assets/racing-poster.jpg" aria-label="AutoDRIVE autonomous racing, ICRA 2025 qualification footage"><source src="./assets/racing-loop.mp4" type="video/mp4"></video><button class="play-toggle" data-video="hero-video" hidden aria-label="Pause racing footage">Ⅱ</button></div><div class="race-caption"><div><span class="caption-title">Sole builder · simulation competition</span><span class="conference-name">IEEE International Conference on Robotics and Automation</span></div></div><div class="race-stats"><div><strong>3<span>rd</span></strong><span>Qualification</span></div><div><strong>0</strong><span>Collisions</span></div><div><strong>81.32<span>s</span></strong><span>Run time</span></div></div><p class="race-technical">MPCC comparison, modified PPO/SAC and multi-head attention; controller training through ROS 2 integration.</p><div class="source-links">${link('Watch run & read the build','./projects/autonomous-racing.html')}${external('Official results','https://autodrive-ecosystem.github.io/competitions/roboracer-sim-racing-icra-2025/#results')}</div></div></div></section>
  <section class="wrap reviewer-work" id="work"><div class="compact-heading"><span class="eyebrow">Selected engineering</span><h2>What I built. What it enables.</h2></div>${['machine-evidence','reinforcement-learning','control-runtime'].map(id=>reviewCard(projects.find(p=>p.id===id))).join('')}<div class="more-work"><p>Also built: ${link('physical golf-cart autonomy','./projects/golf-cart.html')}, ${link('multi-robot execution','./projects/multi-robot-runtime.html')} and ${link('geometric verification','./projects/verification-engine.html')}.</p>${link('All work & experiments','./work.html')}</div></section>
  <section class="wrap current-focus"><div><span class="eyebrow">Building now / Industry 6.0</span><h2>From a production goal<br>to verified machine work.</h2></div><div><p>My second company is in stealth. I’m working on how industrial systems translate an intended outcome into machine actions, recover when execution diverges and verify the physical result.</p><p>The technical question: how much of that work can transfer when the machine, fixture or task changes?</p>${link('Research questions & evaluation','./direction.html')}</div></section>${contact()}</div>`;
}

function projectPage(project,projects) {
  const p=project;const group=projects.filter(x=>x.featured===p.featured&&!x.relatedTo);const next=p.relatedTo?projects.find(x=>x.id===p.relatedTo):group[(group.findIndex(x=>x.id===p.id)+1)%group.length];
  return `<section class="wrap page-intro project-intro"><a class="back-link mono" href="../${p.featured||p.relatedTo?'work':'archive'}.html">← ${p.featured||p.relatedTo?'Flagship work':'Experiments & archive'}</a><div class="detail-topline mono"><span>${p.number} / ${esc(p.category)}</span><span>${esc(p.year)}</span></div><h1>${esc(p.review.title)}</h1><p class="page-deck">${esc(p.review.outcome)}</p><div class="project-facts"><div><span class="mono">System</span><strong>${esc(p.name)}</strong></div><div><span class="mono">My contribution</span><strong>${esc(p.role)}</strong></div><div><span class="mono">Access</span><strong>${esc(p.access)}</strong></div></div></section>
  <div class="wrap detail-layout"><aside class="detail-nav"><span class="eyebrow">Inside the system</span><nav aria-label="Project sections"><a href="#overview">Overview</a>${['race','control'].includes(p.kind)?'<a href="#evidence">Evidence</a>':''}<a href="#technical-details">Technical deep dive</a></nav>${p.repo?external('View implementation',p.repo,'button'):''}</aside><article class="project-body"><section id="overview"><span class="eyebrow">Engineering & evidence</span><p class="lead-copy">${esc(p.review.mechanism)}</p><p class="review-proof">${esc(p.review.evidence)}</p>${p.relatedId?`<p class="related-project">${link(esc(p.relatedLabel),'./'+p.relatedId+'.html')}</p>`:''}${p.kind==='race'?`<figure class="project-media"><video controls playsinline preload="none" poster="../assets/racing-poster.jpg" aria-label="ICRA 2025 qualification footage excerpt"><source src="../assets/icra-qualification.mp4" type="video/mp4"></video><figcaption>ICRA 2025 RoboRacer Sim Racing League · qualification footage excerpt</figcaption></figure><div class="result-strip"><div><strong>81.32 s</strong><span>Qualification run</span></div><div><strong>0</strong><span>Collisions</span></div><div><strong>8.03 s</strong><span>Best lap</span></div></div>`:''}</section>${p.id==='golf-cart'?golfCartMedia('../'):p.id==='multi-robot-runtime'?amrMedia('../'):''}${projectEvidence(p)}<details class="technical-disclosure" id="technical-details"><summary>Technical deep dive <span>Architecture, implementation & tradeoffs</span></summary><section id="architecture"><span class="eyebrow">System architecture</span>${systemArchitecture(p)}</section>${p.sections.map(([h,items],i)=>`<section id="section-${i}"><span class="eyebrow">0${i+1} / ${esc(p.sectionLabels?.[i]||'Implementation')}</span><h2>${esc(h)}</h2>${list(items)}</section>`).join('')}<section class="engineering-note" id="engineering-note"><span class="eyebrow">Engineering note</span><h2>${esc(p.noteTitle)}</h2><p>${esc(p.note)}</p></section></details><section class="scope-note"><span class="mono">Project context</span><p>${esc(p.boundary)}</p><div class="source-links">${p.repo?external('Source on GitHub',p.repo):''}${p.links.map(([label,url])=>external(label,url)).join('')}</div></section></article></div><section class="wrap next-project"><span class="eyebrow">Keep exploring</span><a href="./${next.id}.html"><h2>${esc(next.title)}</h2><span aria-hidden="true">↗</span></a><p>${esc(next.name)}</p></section>`;
}

function about() {
  return `<section class="wrap page-intro life-intro"><span class="eyebrow">Kaustubh Krishna / Off the clock, mostly</span><h1>Life so far.</h1><p class="page-deck">A few milestones. Several bugs. Still running.</p></section><section class="wrap life-timeline" id="timeline" aria-label="Life timeline">${timelineHTML()}</section>
  <section class="wrap section"><div class="section-heading"><span class="eyebrow">Home videos, with motors</span><h2>Before the bigger wheels.</h2><p>Actual footage. The robots were smaller. The enthusiasm was not.</p></div><div class="archive-grid"><figure><video controls playsinline preload="none" poster="./assets/early-robot.jpeg" aria-label="Early PID line-following robot test"><source src="./assets/early-pid.mp4" type="video/mp4"></video><figcaption>PID line-following test · personal project archive</figcaption></figure><figure><video id="wro-demo" controls muted playsinline preload="none" poster="./assets/wro-demo-poster.jpg" aria-label="World Robot Olympiad robot test, silent at 1.25 times speed"><source src="./assets/wro-demo-silent-125.mp4" type="video/mp4"></video><figcaption>World Robot Olympiad robot test · 1.25× speed · silent</figcaption></figure></div><details class="archive-detail"><summary>WRO India 2019 · regional Junior second place <span aria-hidden="true">+</span></summary><img src="./assets/wro-robot.jpeg" alt="WRO India 2019 plaque: second position, Junior Regional Championship" width="814" height="1280" loading="lazy"></details></section>
  ${contact()}`;
}
function direction() {
  return `<section class="wrap page-intro"><span class="eyebrow">Research direction / Second company in stealth</span><h1>Make machine work<br>transferable and verifiable.</h1><p class="page-deck">Industry 6.0 is my long-term ambition. The research problem is concrete: preserve a task’s intended outcome when its machine, fixture or operating conditions change.</p></section><section class="wrap thesis-contract"><span class="mono">Working representation</span><code>task = outcome + constraints + preconditions + actions + acceptance</code><p>A command acknowledgement does not establish that the physical outcome occurred. Completion needs observations tied to the task’s acceptance conditions.</p></section><section class="wrap section"><div class="direction-questions">${[
['01','Bind intent to a real machine.','Represent target state, units, geometry and tolerances; bind process steps to available resources. Evaluate mapping effort and task completion after a machine or fixture change.'],
['02','Learn where prediction changes action.','Use learned dynamics for action selection and recovery. Compare against classical control under the same constraints: rollout error, task success, tail latency and failure cases.'],
['03','Recover with evidence.','Invalidate dependent steps after physical state changes. Test interrupted motion, stale observations and missing evidence; measure detection and recovery, and withhold unsupported verdicts.']
].map(([n,h,p])=>`<div class="direction-question"><span class="mono">${n}</span><div><h3>${h}</h3><p>${p}</p></div></div>`).join('')}</div><p class="direction-closing">These are research questions and evaluation criteria. The ${link('engineering case studies','./work.html')} document work built so far.</p></section>${contact()}`;
}

export function renderSite(root) {
  const projects=JSON.parse(readFileSync(root+'/content/projects.json','utf8'));
  const pages=new Map();
  const add=(path,title,description,body,active='')=>pages.set(path,layout({path,title,description,body,active}));
  add('index.html','Founder & robotics engineer','Kaustubh Krishna builds autonomous vehicles, robot learning systems and industrial verification. ICRA qualification result, public code and measured control. Second company in stealth.',home(projects));
  add('work.html','Engineering work','Autonomous racing, robot learning, control and industrial verification: outcomes, mechanisms and evidence.',`<section class="wrap page-intro"><span class="eyebrow">Work</span><h1>Robotics & industrial systems.</h1><p class="page-deck">What each system does, how I built it, and the evidence behind it.</p></section><section class="wrap reviewer-work work-catalogue">${projects.filter(p=>p.featured).map(p=>reviewCard(p)).join('')}<div class="more-work">${link('Other experiments: visual driving, native inference & compute','./archive.html')}</div></section>`, 'Work');
  add('archive.html','Experiments & archive','Visual driving, native speech inference and private compute experiments.',`<section class="wrap page-intro"><span class="eyebrow">Experiments & archive</span><h1>Other systems.<br>Same curiosity.</h1><p class="page-deck">Work in visual driving, native inference and access infrastructure, alongside the main robotics programme.</p><a class="text-link" href="./work.html">Back to flagship work ↗</a></section><section class="wrap section"><div class="project-grid">${projects.filter(p=>!p.featured&&!p.relatedTo).map(p=>projectCard(p)).join('')}</div></section>`,'Work');
  add('about.html','Life so far','Hello World in 2006. Two Pentium PCs, first programs, robot competitions and two startups. The short version of Kaustubh Krishna’s life so far.',about(),'Life so far');
  add('direction.html','Industry 6.0 & autonomous factories','Building toward general industrial intelligence: systems that interpret production goals, coordinate machines, recover and verify physical outcomes.',direction(),'Direction');
  for(const p of projects) add('projects/'+p.id+'.html',p.name,p.subtitle,projectPage(p,projects),'Work');
  pages.set('rlx-core.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0;url=./projects/reinforcement-learning.html"><link rel="canonical" href="${canonical}projects/reinforcement-learning.html"><title>Reinforcement Learning Toolkit · Kaustubh Krishna</title></head><body><p>This project is now the <a href="./projects/reinforcement-learning.html">Reinforcement Learning Toolkit</a>.</p></body></html>`);
  add('404.html','Page not found','Find Kaustubh Krishna’s projects in robotics and Physical AI.',`<section class="wrap page-intro"><span class="eyebrow">404 / Unmapped territory</span><h1>Let’s get you<br>back on track.</h1><p class="page-deck">That page has moved or doesn’t exist.</p>${link('Explore the work',canonical+'work.html','button primary')}</section>`);
  add('full-context.html','Full portfolio context','Complete public portfolio in one page: all projects, technical details, results, life story and source links.',contextDocuments(pages).body);
  return pages;
}
